### ISSUE TITLE
Casino 작업

### ISSUE THREAD

**Issue by cbj0010** [woorifisa-service-dev-3rd/backend-1st-casino#1]
### ✏ Todo

- [x] player run
- [x] player가 홀,짝을 선택할 수 있도록
- [x] 게임에서 홀,짝을 맞춘 경우를 가져와서 배팅금액을 올려준다
- [ ] 현재 소유한 금액을 기준으로 게임을 다시 할 말 고르기
