### ISSUE TITLE
은행 상환 조회

### ISSUE THREAD

**Issue by cbj0010** [woorifisa-service-dev-3rd/backend-1st-casino#2]
## 📢 Issue

대출 선택 시 은행 상환 조회

### ✏ Todo

- [ ] player가 대출을 선택하면 자동으로 1000만원을 지급한다.
- [ ] 10판 이내에 갚을 수 있도록 설정하고, 10판이 지나면 player의 잔액에서 1000만원을 상환하도록 한다.
- [ ] 1000만원을 상환 했을 때 잔액이 0원 이하라면, 게임이 종료된다.
