### ISSUE TITLE
player 작업

### ISSUE THREAD

**Issue by bangsk2** [woorifisa-service-dev-3rd/backend-1st-casino#3]
### ✏ Todo

- [x] player 이름을 입력
- [x] player 잔액이 1000만원으로 저장
- [x] player 가 메뉴를 선택(a, b, c)
